spring.application.name=MailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rbu9032@gmail.com
spring.mail.password=xcco zidp cvjz fyxv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
