spring.application.name=OrderManagement
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/raghu
spring.datasource.password=1218
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.info.name=Raghu
spring.info.password=Norumusko
logging.level.root=INFO
logging.level.com.rbu.service.impl.OrderServiceImpl=TRACE
logging.file.name=orderlogs
logging.file.path=/logs
#logging.pattern.file=%d(yyyy/MM/dd HH:mm:ss) %-5level {%thread} %logger{20} - %msg%n
server.port=8081

#enabling spring boot actuator
management.endpoints.web.exposure.include=*
info.app.name=OrderManagement
info.app.version=1.0.0
info.app.life=10
management.info.env.enabled=true

management.server.port=13000